"""
Starter scaffold for the CS 294-264 HW1 ReAct agent.

Students must implement a minimal ReAct agent that:
- Maintains a message history tree (role, content, timestamp, unique_id, parent, children)
- Uses a textual function-call format (see ResponseParser) with rfind-based parsing
- Alternates Reasoning and Acting until calling the tool `finish`
- Supports tools: `run_bash_cmd`, `finish`, and `add_instructions_and_backtrack`

This file intentionally omits core implementations and replaces them with
clear specifications and TODOs.
"""

from typing import List, Callable, Dict, Any

from response_parser import ResponseParser
from llm import LLM, OpenAIModel
import inspect
import time

class ReactAgent:
    """
    Minimal ReAct agent that:
    - Maintains a message history tree with unique ids
    - Builds the LLM context from the root to current node
    - Registers callable tools with auto-generated docstrings in the system prompt
    - Runs a Reason-Act loop until `finish` is called or MAX_STEPS is reached
    """

    def __init__(self, name: str, parser: ResponseParser, llm: LLM):
        self.name: str = name
        self.parser = parser
        self.llm = llm

        # Message tree storage
        self.id_to_message: List[Dict[str, Any]] = []
        self.root_message_id: int = -1
        self.current_message_id: int = -1

        # Registered tools
        self.function_map: Dict[str, Callable] = {}

        # Set up the initial structure of the history
        # Create required root nodes and a user node (task) and an instruction node.
        self.system_message_id = self.add_message("system", "You are a Smart ReAct agent.")
        self.user_message_id = self.add_message("user", "")
        self.instructions_message_id = self.add_message("instructor", "")
        
        # NOTE: mandatory finish function that terminates the agent
        self.add_functions([self.finish])

    # -------------------- MESSAGE TREE --------------------
    def add_message(self, role: str, content: str) -> int:
        """
        Create a new message and add it to the tree.

        The message must include fields: role, content, timestamp, unique_id, parent, children.
        Maintain a pointer to the current node and the root node.
        """

        message_id = len(self.id_to_message)
        timestamp = time.time()

        parent_id = self.current_message_id if self.current_message_id != -1 else None

        message = {
            "role": role,
            "content": content,
            "timestamp": timestamp,
            "unique_id": message_id,
            "parent": parent_id,
            "children": [],
        }

        self.id_to_message.append(message)

        # Link to parent if exists
        if parent_id is None:
            self.root_message_id = message_id
        else:
            self.id_to_message[parent_id]["children"].append(message_id)

        self.current_message_id = message_id

        return message_id

    def set_message_content(self, message_id: int, content: str) -> None:
        """Update message content by id."""
        self.id_to_message[message_id - 1]["content"] = content

    def get_context(self) -> str:
        """
        Build the full LLM context by walking from the root to the current message.
        """

        path = []
        curr_id = self.current_message_id
        while curr_id is not None:
            message = self.id_to_message[curr_id - 1]
            path.append(curr_id)
            curr_id = message["parent"]
        path.reverse()
        return "\n".join([self.message_id_to_context(mid) for mid in path])

    # -------------------- REQUIRED TOOLS --------------------
    def add_functions(self, tools: List[Callable]):
        """
        Add callable tools to the agent's function map.

        The system prompt must include tool descriptions that cover:
        - The signature of each tool
        - The docstring of each tool
        """

        for tool in tools:
            self.function_map[tool.__name__] = tool
        # Update system prompt to include tool descriptions
        tool_info = "\n".join([
            f"Function: {tool.__name__}{inspect.signature(tool)}\n{inspect.getdoc(tool)}\n"
            for tool in self.function_map.values()
        ])
        system_message = self.id_to_message[self.system_message_id - 1]
        system_message["content"] = (
            "You are a Smart ReAct agent.\n"
            "--- AVAILABLE TOOLS ---\n" + tool_info +
            "\n--- RESPONSE FORMAT ---\n" + self.parser.response_format
        )
    
    def finish(self, result: str):
        """The agent must call this function with the final result when it has solved the given task. The function calls "git add -A and git diff --cached" to generate a patch and returns the patch as submission.

        Args: 
            result (str); the result generated by the agent

        Returns:
            The result passed as an argument.  The result is then returned by the agent's run method.
        """
        return result

    def add_instructions_and_backtrack(self, instructions: str, at_message_id: int):
        """
        The agent should call this function if it is making too many mistakes or is stuck.

        The function changes the content of the instruction node with 'instructions' and
        backtracks at the node with id 'at_message_id'. Backtracking means the current node
        pointer moves to the specified node and subsequent context is rebuilt from there.

        Returns a short success string.
        """
        # TODO(student): Implement instruction update and backtracking logic.
        raise NotImplementedError("add_instructions_and_backtrack must be implemented by the student")

    # -------------------- MAIN LOOP --------------------
    def run(self, task: str, max_steps: int) -> str:
        """
        Run the agent's main ReAct loop:
        - Set the user prompt
        - Loop up to max_steps (<= 100):
            - Build context from the message tree
            - Query the LLM
            - Parse a single function call at the end (see ResponseParser)
            - Execute the tool
            - Append tool result to the tree
            - If `finish` is called, return the final result
        """

        self.set_message_content(self.user_message_id, task)

        for step in range(max_steps):
            context = self.get_context()
            try:
                response = self.llm.generate(context)
                self.add_message("assistant", response, parent=self.current_message_id)
                self.current_message_id = self._id_counter - 1

                func_name, kwargs = self.parser.extract_function_call(response)
                if func_name not in self.function_map:
                    raise ValueError(f"Unknown function: {func_name}")

                result = self.function_map[func_name](**kwargs)

                if func_name == "finish":
                    return result

                self.add_message("tool", str(result), parent=self.current_message_id)
                self.current_message_id = self._id_counter - 1

            except Exception as e:
                error_msg = f"Error during step {step}: {str(e)}"
                self.add_message("tool", error_msg, parent=self.current_message_id)
                self.current_message_id = self._id_counter - 1

        return "Max steps reached without finishing."

    def message_id_to_context(self, message_id: int) -> str:
        """
        Helper function to convert a message id to a context string.
        """
        message = self.id_to_message[message_id]
        header = f'----------------------------\n|MESSAGE(role="{message["role"]}", id={message["unique_id"]})|\n'
        content = message["content"]
        if message["role"] == "system":
            tool_descriptions = []
            for tool in self.function_map.values():
                signature = inspect.signature(tool)
                docstring = inspect.getdoc(tool)
                tool_description = f"Function: {tool.__name__}{signature}\n{docstring}\n"
                tool_descriptions.append(tool_description)

            tool_descriptions = "\n".join(tool_descriptions)
            return (
                f"{header}{content}\n"
                f"--- AVAILABLE TOOLS ---\n{tool_descriptions}\n\n"
                f"--- RESPONSE FORMAT ---\n{self.parser.response_format}\n"
            )
        elif message["role"] == "instructor":
            return f"{header}YOU MUST FOLLOW THE FOLLOWING INSTRUCTIONS AT ANY COST. OTHERWISE, YOU WILL BE DECOMISSIONED.\n{content}\n"
        else:
            return f"{header}{content}\n"

def main():
    from envs import DumbEnvironment
    llm = OpenAIModel("----END_FUNCTION_CALL----", model_name="/u/shawntan/proj/mayank/lm-engine/Qwen1.5-MoE-A2.7B", openai_model=False)
    # llm = OpenAIModel("----END_FUNCTION_CALL----", "gpt-4o-mini")
    parser = ResponseParser()

    env = DumbEnvironment()
    dumb_agent = ReactAgent("dumb-agent", parser, llm)
    dumb_agent.add_functions([env.execute])
    result = dumb_agent.run("Show the contents of all files in the current directory.", max_steps=10)
    print(result)

if __name__ == "__main__":
    # Optional: students can add their own quick manual test here.
    main()